// The API contract: every request and response body the frontend and the
// FastAPI backend exchange, plus the messages between the API and the EC2
// workers. The Pydantic models in api/ should mirror these names and fields.
//
// Conventions for the Python side:
// - JSON is camelCase. Give every model
//   `model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)`
//   so Python can use snake_case attributes (`file_name`) while the JSON
//   says `fileName`.
// - `Id` -> uuid.UUID, `IsoDateTime` -> datetime (timezone-aware, UTC).
// - A string union like `'queued' | 'ready'` -> Literal["queued", "ready"].
// - `T | null` -> `T | None` (always present in the JSON, may be null).
// - TranscodeSettings comes from src/config/transcodeOptions.ts. Each field's
//   allowed values are the `value`s in that file's option lists. Validate them
//   with Literal types so nothing else can reach FFmpeg.

import type { TranscodeSettings } from '../config/transcodeOptions.ts'

export type { TranscodeSettings }

/** Server-generated UUID. Never accept one from the client as a new resource id. */
export type Id = string

/** ISO 8601 timestamp in UTC, e.g. "2026-10-07T18:30:00Z". */
export type IsoDateTime = string

/**
 * Error body for 4xx/5xx responses (FastAPI's HTTPException format).
 * FastAPI's own 422 validation errors use a list for `detail` instead;
 * the client falls back to a generic message for those.
 */
export type ApiErrorBody = {
  detail: string
}

// ---------------------------------------------------------------------------
// Health: GET /health
// ---------------------------------------------------------------------------

export type HealthResponse = {
  status: 'ok'
}

// ---------------------------------------------------------------------------
// Auth: /auth/*
// The session lives in an httpOnly, Secure, SameSite cookie that the API sets
// on login/signup. No token ever appears in a response body.
// ---------------------------------------------------------------------------

export type User = {
  id: Id
  email: string
  createdAt: IsoDateTime
}

/** Body for POST /auth/login and POST /auth/signup. */
export type Credentials = {
  email: string
  password: string
}

// ---------------------------------------------------------------------------
// Uploads: POST /uploads
// Step 1 of encoding. The API returns a presigned S3 POST so the browser
// uploads the video straight to S3. The video never passes through the API,
// and S3 enforces the size limit and content type through the policy.
// ---------------------------------------------------------------------------

export type CreateUploadRequest = {
  fileName: string // display only; the S3 key is generated server-side
  contentType: 'video/mp4'
  sizeBytes: number
}

export type UploadTicket = {
  uploadId: Id
  url: string // S3 presigned POST URL
  fields: Record<string, string> // form fields S3 requires, sent before the file
  maxSizeBytes: number
  expiresAt: IsoDateTime
}

// ---------------------------------------------------------------------------
// Jobs: /jobs/*
// Step 2 of encoding, and everything the Library tab shows. Creating a job is
// what starts the AWS work: the API enqueues a WorkerJobMessage on SQS and,
// if needed, launches or scales up EC2 workers. There is deliberately no
// public endpoint that starts workers directly.
// ---------------------------------------------------------------------------

export type JobStatus = 'queued' | 'processing' | 'ready' | 'failed'

export type CreateJobRequest = {
  uploadId: Id
  settings: TranscodeSettings
  transcribe: boolean
}

export type Job = {
  id: Id
  status: JobStatus
  fileName: string
  settings: TranscodeSettings
  transcribe: boolean
  createdAt: IsoDateTime
  updatedAt: IsoDateTime
  expiresAt: IsoDateTime // matches the S3 lifecycle rule that deletes outputs
  outputSizeBytes: number | null // null until the encode finishes
  hasTranscript: boolean
  error: string | null // user-safe message when status is 'failed'
}

export type DownloadFile = 'video' | 'transcript'

/** Response for GET /jobs/{jobId}/download?file=video|transcript. */
export type DownloadLink = {
  url: string // short-lived presigned S3 GET URL (Content-Disposition: attachment)
  expiresAt: IsoDateTime
}

// ---------------------------------------------------------------------------
// Worker contract (backend only; the frontend never sends or receives these)
// Documented here so the API and the workers share one definition.
// ---------------------------------------------------------------------------

/**
 * SQS message body the API enqueues when a job is created.
 * - Every value comes from the server: userId from the session, keys
 *   generated by the API. Nothing is copied unchecked from the request.
 * - The bucket and queue names come from the worker's environment, not the
 *   message, so a forged message can't point a worker at another bucket.
 * - SQS can deliver a message more than once, so workers must treat a jobId
 *   they've already finished as done.
 */
export type WorkerJobMessage = {
  schemaVersion: 1
  jobId: Id
  userId: Id
  inputKey: string // e.g. "uploads/<userId>/<uploadId>.mp4"
  outputPrefix: string // e.g. "outputs/<userId>/<jobId>/"
  settings: TranscodeSettings
  transcribe: boolean
  requestedAt: IsoDateTime
}

/** Progress a worker reports while it runs (moves the job to 'processing'). */
export type WorkerJobStarted = {
  schemaVersion: 1
  jobId: Id
  workerId: string // EC2 instance id
  startedAt: IsoDateTime
}

/**
 * What a worker reports when it finishes. How it's delivered is still open:
 * a direct write to the job table with the worker's IAM role, or a result
 * queue the API consumes. `error` holds internal detail for logs; the API
 * maps it to the user-safe `Job.error`.
 */
export type WorkerJobResult = {
  schemaVersion: 1
  jobId: Id
  status: 'ready' | 'failed'
  outputKey: string | null
  transcriptKey: string | null
  outputSizeBytes: number | null
  durationSeconds: number | null // length of the source video
  error: string | null
  finishedAt: IsoDateTime
}
